---
development:
  dialect: postgres
  database: buffalo_development
  user: postgres
  password: p0stgr3s
  host: 127.0.0.1
  pool: 5
  sslmode: require

test:
  url: {{envOr "DATABASE_URL" "postgres://postgres:p0stgr3s@127.0.0.1:5432/buffalo_test?sslmode=require"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:p0stgr3s@127.0.0.1:5432/buffalo_production?sslmode=require"}}
