version: "3.7"
services:
  web:
    image: "ghcr.io/todos-api/buffalo:docker-image"
    environment:
      PORT: "3000"
      GO_ENV: "production"
      DATABASE_URL: "postgres://postgres:p0stgres@db/app"
    ports:
    - "3000:3000"
    command:
    - "/bin/app"
    depends_on:
    - "db"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: "10s"
        order: "start-first"
      resources:
        limits:
          cpus: "0.50"
          memory: "256Mi"
        reservations:
          cpus: "0.50"
          memory: "256Mi"
      restart_policy:
        condition: "on-failure"
        delay: "5s"
        max_attempts: 3
        window: "60s"

  migrate:
    image: "ghcr.io/todos-api/buffalo:docker-image"
    environment:
      GO_ENV: "production"
      DATABASE_URL: "postgres://postgres:p0stgres@db/app"
    command:
    - "/bin/app"
    - "migrate"
    depends_on:
    - "db"
    deploy:
      restart_policy:
        condition: "none"
        max_attempts: 0

  db:
    image: "ghcr.io/infrastructure-as-code/postgres:12-alpine"
    environment:
      POSTGRES_DB: "app"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p0stgres
