name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - go_version: "1.14"
          - go_version: "1.15"
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: test
          POSTGRES_PASSWORD: postgres
        ports:
          - "5432:5432"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}

      - name: install buffalo
        runs: |
          go get github.com/gobuffalo/buffalo/buffalo
          go mod download
          buffalo version
